#!/bin/sh
docker run 	--rm -it 			\
		-v $(pwd)/work:/home/pytfa/work \
		-v $(pwd)/../../pytfa:/src/pytfa	\
        -v $(pwd)/..:/src/etfl  \
        -v $(pwd)/src/optlang:/src/optlang  \
		etfl-docker
